"""0001_initial_schema

Revision ID: 0c0c5ce46f4c
Revises: 
Create Date: 2026-09-27 22:53:09.579366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0c5ce46f4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_frameworks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_framework_name_version')
    )
    with op.batch_alter_table('compliance_frameworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_frameworks_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('COMPLIANCE_OFFICER', 'ADMIN', 'AUDITOR', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('evidence_documents',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('POLICY', 'AUDIT_LOG', 'CERTIFICATE', 'CONFIG', 'OTHER', name='document_type_enum', native_enum=False), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('validity_status', sa.Enum('VALID', 'EXPIRING_SOON', 'EXPIRED', name='evidence_validity_enum', native_enum=False), nullable=False),
    sa.Column('processing_status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'PROCESSED', 'FAILED', name='processing_status_enum', native_enum=False), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_hash', ['file_hash'], unique=False)
        batch_op.create_index('ix_evidence_status', ['processing_status'], unique=False)
        batch_op.create_index('ix_evidence_validity_dates', ['valid_from', 'expires_at'], unique=False)

    op.create_table('requirements',
    sa.Column('framework_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', 'requirement_code', name='uq_requirement_framework_code')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index('ix_requirements_framework_active', ['framework_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_framework_id'), ['framework_id'], unique=False)

    op.create_table('document_processing_jobs',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='job_status_enum', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_processing_jobs_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index('ix_jobs_status_scheduled', ['status', 'scheduled_at'], unique=False)

    op.create_table('evidence_matches',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('SATISFIED', 'PARTIAL', 'GAP', name='compliance_status_enum', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence score from model (recorded strictly as audit metadata).'),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', sa.JSON(), nullable=False, comment='Array of direct quotes extracted from evidence.'),
    sa.Column('missing_evidence', sa.JSON(), nullable=False, comment='Array of unmet criteria.'),
    sa.Column('requested_evidence', sa.JSON(), nullable=False, comment='Array of recommended remediations.'),
    sa.Column('citation_verified', sa.Boolean(), nullable=False, comment='True if quotes were deterministically verified against raw document text.'),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_evidence', ['evidence_id'], unique=False)
        batch_op.create_index('ix_matches_req_eval', ['requirement_id', 'evaluated_at'], unique=False)

    op.create_table('compliance_status',
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('current_match_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('SATISFIED', 'PARTIAL', 'GAP', name='compliance_status_enum', native_enum=False), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_match_id'], ['evidence_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_status_requirement_id'), ['requirement_id'], unique=True)
        batch_op.create_index('ix_compliance_status_val', ['status'], unique=False)

    op.create_table('compliance_status_history',
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.Enum('SATISFIED', 'PARTIAL', 'GAP', name='compliance_status_enum', native_enum=False), nullable=True),
    sa.Column('new_status', sa.Enum('SATISFIED', 'PARTIAL', 'GAP', name='compliance_status_enum', native_enum=False), nullable=False),
    sa.Column('evidence_match_id', sa.Uuid(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_match_id'], ['evidence_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_status_history_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index('ix_history_req_date', ['requirement_id', 'recorded_at'], unique=False)

    op.create_table('gap_reports',
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_match_id', sa.Uuid(), nullable=True),
    sa.Column('gap_type', sa.Enum('MISSING_EVIDENCE', 'AMBIGUOUS_EVIDENCE', 'EXPIRED_EVIDENCE', 'PARTIAL_COVERAGE', name='gap_type_enum', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_evidence', sa.JSON(), nullable=False, comment='Specific evidence documents or configurations requested from user.'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='gap_priority_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'WAIVED', name='gap_status_enum', native_enum=False), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_match_id'], ['evidence_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gap_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gap_reports_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index('ix_gaps_req_status', ['requirement_id', 'status'], unique=False)
        batch_op.create_index('ix_gaps_status_priority', ['status', 'priority'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gap_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_gaps_status_priority')
        batch_op.drop_index('ix_gaps_req_status')
        batch_op.drop_index(batch_op.f('ix_gap_reports_requirement_id'))

    op.drop_table('gap_reports')
    with op.batch_alter_table('compliance_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_history_req_date')
        batch_op.drop_index(batch_op.f('ix_compliance_status_history_requirement_id'))

    op.drop_table('compliance_status_history')
    with op.batch_alter_table('compliance_status', schema=None) as batch_op:
        batch_op.drop_index('ix_compliance_status_val')
        batch_op.drop_index(batch_op.f('ix_compliance_status_requirement_id'))

    op.drop_table('compliance_status')
    with op.batch_alter_table('evidence_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_req_eval')
        batch_op.drop_index('ix_matches_evidence')

    op.drop_table('evidence_matches')
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_scheduled')
        batch_op.drop_index(batch_op.f('ix_document_processing_jobs_evidence_id'))

    op.drop_table('document_processing_jobs')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_framework_id'))
        batch_op.drop_index('ix_requirements_framework_active')

    op.drop_table('requirements')
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_validity_dates')
        batch_op.drop_index('ix_evidence_status')
        batch_op.drop_index('ix_evidence_hash')

    op.drop_table('evidence_documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('compliance_frameworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_frameworks_is_active'))

    op.drop_table('compliance_frameworks')
    # ### end Alembic commands ###
